<?PHP
/*    
	This file is part of STFC.
	Copyright 2006-2007 by Michael Krauss (info@stfc2.de) and Tobias Gafner
		
	STFC is based on STGC,
	Copyright 2003-2007 by Florian Brede (florian_brede@hotmail.com) and Philipp Schmidt
	
    STFC is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    STFC is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


// This file was automatically created by create_static_components.php on April 8, 2005, 3:30 am


$ship_components=array(
// Race Breen
8=>array(
        // Category Convertitore
        0=>array(
             // Component Bioconvertitore MK I
             0=>array(
                    'name'=>'Bioconvertitore MK I',
                    'resource_1'=>'1050',
                    'resource_2'=>'525',
                    'resource_3'=>'300',
                    'resource_4'=>'25',
                    'buildtime'=>'14',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'1',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'1',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'8',
                    'value_14'=>'0',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'1',
                    'torso_3'=>'1',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'0',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Il bioconvertitore di base consente di produrre energia a costi contenuti, grazie all&#146;insostitubile contributo volontario del nostro popolo.',
                    'dev_info'=>'',
            ), // Endof Component Bioconvertitore MK I

             // Component Bioconvertitore MK II
             1=>array(
                    'name'=>'Bioconvertitore MK II',
                    'resource_1'=>'1800',
                    'resource_2'=>'825',
                    'resource_3'=>'225',
                    'resource_4'=>'30',
                    'buildtime'=>'17',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'3',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'1',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'22',
                    'value_14'=>'0',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Progettata per le navi da guerra, la versione potenziata del bioconvertitore permette di far fronte a fabbisogni energetici pi&ugrave; consistenti, sebbene richieda costi di produzione e impegni volontari leggermente maggiori.',
                    'dev_info'=>'',
            ), // Endof Component Bioconvertitore MK II

             // Component Bioconvertitore MK III
             2=>array(
                    'name'=>'Bioconvertitore MK III',
                    'resource_1'=>'3750',
                    'resource_2'=>'2250',
                    'resource_3'=>'900',
                    'resource_4'=>'40',
                    'buildtime'=>'25',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'5',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'2',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'24',
                    'value_14'=>'0',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'0',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'La versione definitiva del bioconvertitore &egrave; un componente insostituibile della Gor&acute;Taan, l&#146;orgoglio delle nostre navi, poich&eacute; fornisce un discreto contributo al nucleo di curvatura, oltre a sopperire al suo elevato fabbisogno energetico. Non vi &egrave; alcun dubbio che ci&ograve; ne giustifichi sia gli alti costi di produzione che uno spirito di abnegazione ampiamente diffuso.',
                    'dev_info'=>'',
            ), // Endof Component Bioconvertitore MK III

      'name'=>'Bioconvertitore',
      'num'=>'3',
      ), // Endof Category Convertitore


        // Category Curvatura
        1=>array(
             // Component Bionucleo di curvatura MK I
             0=>array(
                    'name'=>'Nucleo di curvatura MK I',
                    'resource_1'=>'750',
                    'resource_2'=>'112.5',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'1',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'0',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'1',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'5',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'1',
                    'torso_3'=>'1',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Il nucleo di curvatura di base consente a tutte le nostre navi di rendere nota a tutta la galassia la nostra potenza con maggiore alacrit&agrave; e costi irrisori.',
                    'dev_info'=>'',
            ), // Endof Component Bionucleo di curvatura MK I

             // Component Bionucleo di curvatura MK II
             1=>array(
                    'name'=>'Nucleo di curvatura MK II',
                    'resource_1'=>'750',
                    'resource_2'=>'112.5',
                    'resource_3'=>'0',
                    'resource_4'=>'10',
                    'buildtime'=>'8',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'0',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'3',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'9',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'La versione superiore del nucleo di curvatura viene utilizzata dalle nostre navi da guerra allo scopo di diffondere la presenza della Confederazione tra le razze imbelli pi&ugrave; velocemente, anche se la sua composizione a base prevalentemente organica prevede l&#146;utilizzo di entusiasti volontari.',
                    'dev_info'=>'',
            ), // Endof Component Bionucleo di curvatura MK II

             // Component Bionucleo di curvatura MK III
             2=>array(
                    'name'=>'Nucleo di curvatura MK III',
                    'resource_1'=>'1125',
                    'resource_2'=>'300',
                    'resource_3'=>'75',
                    'resource_4'=>'15',
                    'buildtime'=>'11',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'1',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'5',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'9',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'0',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Questa versione del nucleo di curvatura viene utilizzata esclusivamente dalle possenti Gor&acute;Taan, allo scopo di compensarne l&#146;eccessiva lentezza. I costi di produzione sono elevati, ma la Confederazione richiede doverosi sacrifici al nostro popolo.',
                    'dev_info'=>'',
            ), // Endof Component Bionucleo di curvatura MK III

      'name'=>'Nucleo di curvatura',
      'num'=>'3',
      ), // Endof Category Curvatura


        // Category Ponte armi I
        2=>array(
             // Component Dissipatore di energia
             0=>array(
                    'name'=>'Dissipatore di energia',
                    'resource_1'=>'0',
                    'resource_2'=>'0',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'15',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'0',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'100',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'5',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'0',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Il dissipatore di energia &eacute; un componente standard della Gor&acute;Taan, il quale ha sempre avuto un ruolo determinante per l&#146;egemonia della Confederazione sulle razze vili e codarde. Esso sottrae direttamente energia al nucleo di curvatura delle navi nemiche al fine di potenziare gli armamenti della nave sulla quale viene installato.',
                    'dev_info'=>'',
            ), // Endof Component Dissipatore di energia

      'name'=>'Ponte armi I',
      'num'=>'1',
      ), // Endof Category Ponte armi I


        // Category Ponte armi II
        3=>array(
             // Component Lanciagranate di base
             0=>array(
                    'name'=>'Lanciagranate di base',
                    'resource_1'=>'750',
                    'resource_2'=>'0',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'6',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'1',
                    'unit_6'=>'0',
                    'value_1'=>'8',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'1',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'1',
                    'torso_3'=>'1',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Potenziamento elementare per le nostre navi, dagli effetti assai limitati sugli scudi nemici.',
                    'dev_info'=>'',
            ), // Endof Component Lanciagranate di base

             // Component Lanciagranate migliorato
             1=>array(
                    'name'=>'Lanciagranate migliorato',
                    'resource_1'=>'1500',
                    'resource_2'=>'75',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'8',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'3',
                    'unit_6'=>'0',
                    'value_1'=>'25',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'1',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Miglioramento tecnologico del lanciagranate di base, dagli effetti pi&ugrave; rilevanti.',
                    'dev_info'=>'',
            ), // Endof Component Lanciagranate migliorato

             // Component Lanciagranate a frequenza
             2=>array(
                    'name'=>'Lanciagranate a frequenza',
                    'resource_1'=>'4500',
                    'resource_2'=>'1125',
                    'resource_3'=>'375',
                    'resource_4'=>'30',
                    'buildtime'=>'1',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'2',
                    'unit_6'=>'0',
                    'value_1'=>'20',
                    'value_2'=>'60',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'2',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'0',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Sviluppo a base organica del lanciagranate, destinato alle agili e veloci Gled Kraan. Gli elevati costi, sia in termini di risorse che di valorosi Breen, sono giustificati dalla notevole potenza di fuoco che esso permette.',
                    'dev_info'=>'',
            ), // Endof Component Lanciagranate a frequenza

             // Component Doppio lanciagranate a frequenza
             3=>array(
                    'name'=>'Doppio lanciagranate a frequenza',
                    'resource_1'=>'6750',
                    'resource_2'=>'750',
                    'resource_3'=>'450',
                    'resource_4'=>'30',
                    'buildtime'=>'2',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'1',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'185',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'2',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'0',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Sviluppo a base organica del lanciagranate, destinato alle possenti Gor&#acute;Taan. Gli enormi costi, sia in termini di risorse che di valorosi Breen, sono giustificati dalla notevole potenza di fuoco che esso permette.',
                    'dev_info'=>'',
            ), // Endof Component Doppio lanciagranate a frequenza

      'name'=>'Ponte armi II',
      'num'=>'4',
      ), // Endof Category Ponte armi II


        // Category Scafo/Scudo
        4=>array(
             // Component Scudo
             0=>array(
                    'name'=>'Scudo',
                    'resource_1'=>'225',
                    'resource_2'=>'0',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'1',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'0',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'155',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'2',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Questa &egrave; la forma pi&ugrave; semplice di protezione disponibile per le nostre navi da guerra, richiede costi minimi con risultati relativamente soddisfacenti.',
                    'dev_info'=>'',
            ), // Endof Component Scudo

             // Component Scudo di fase
             1=>array(
                    'name'=>'Scudo fasico',
                    'resource_1'=>'1500',
                    'resource_2'=>'75',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'2',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'0',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'185',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'4',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Gli scudi fasici sono progettati in modo tale da modulare le loro fasi e che vi siano sempre almeno 2 &acute;strati&acute; sovrapposti per evitare la penetrazione dei proiettili.',
                    'dev_info'=>'',
            ), // Endof Component Scudo di fase

             // Component Scudo quantico
             2=>array(
                    'name'=>'Scudo quantico',
                    'resource_1'=>'4500',
                    'resource_2'=>'1125',
                    'resource_3'=>'375',
                    'resource_4'=>'0',
                    'buildtime'=>'5',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'0',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'210',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'5',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Gli scudi quantici sono uno sviluppo della tecnologia degli scudi tradizionali, qui barriere di energia quantica vengono deflesse dallo scafo della nave per prevenire l&#146;attraversamento del campo difensivo.',
                    'dev_info'=>'',
            ), // Endof Component Scudo quantico
            
             // Component Corazza organica MK I
             3=>array(
                    'name'=>'Corazza organica MK I',
                    'resource_1'=>'2625',
                    'resource_2'=>'300',
                    'resource_3'=>'150',
                    'resource_4'=>'0',
                    'buildtime'=>'2',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'0',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'350',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'0',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Con lo scambio di biomassa, &egrave; possibile distruggere le navi nemiche.',
                    'dev_info'=>'',
            ), // Endof Component Corazza organica MK I

             // Component Corazza organica MK II
              4=>array(
                    'name'=>'Corazza organica MK II',
                    'resource_1'=>'375',
                    'resource_2'=>'0',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'2',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'0',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'450',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'0',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'0',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Con lo scambio di biomassa, &egrave; possibile distruggere le navi nemiche.',
                    'dev_info'=>'',
            ), // Endof Component Corazza organica MK II
              
             // Component Corazza organica MK III
              5=>array(
                    'name'=>'Corazza organica MK III',
                    'resource_1'=>'675',
                    'resource_2'=>'37.5',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'5',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'0',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'250',
                    'value_5'=>'750',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'0',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'0',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Con lo scambio di biomassa, &egrave; possibile distruggere le navi nemiche.',
                    'dev_info'=>'',
            ), // Endof Component Corazza organica MK III

      'name'=>'Scafo/Scudo',
      'num'=>'6',
      ), // Endof Category Scafo/Scudo


        // Category Sistema di elaborazione
        5=>array(
             // Component Interfaccia Biogenetica MK I
             0=>array(
                    'name'=>'Interfaccia Biogenetica MK I',
                    'resource_1'=>'1050',
                    'resource_2'=>'150',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'2',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'0',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'1',
                    'value_7'=>'1',
                    'value_8'=>'6',
                    'value_9'=>'6',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'2',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'1',
                    'torso_3'=>'1',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'0',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Sistemi informatici base in dotazione a tutte le navi Breen.',
                    'dev_info'=>'',
            ), // Endof Component Interfaccia Biogenetica

             // Component Interfaccia Biogenetica MK II
             1=>array(
                    'name'=>'Interfaccia Biogenetica MK II',
                    'resource_1'=>'1725',
                    'resource_2'=>'300',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'2',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'0',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'1',
                    'value_7'=>'2',
                    'value_8'=>'3',
                    'value_9'=>'1',
                    'value_10'=>'0',
                    'value_11'=>'2',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'2',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Sistemi informatici migliorati in dotazione alle navi Breen di classe media.',
                    'dev_info'=>'',
            ), // Endof Component Interfaccia Biogenetica MK II

             // Component Interfaccia Biogenetica MK III
             2=>array(
                    'name'=>'Interfaccia Biogenetica MK III',
                    'resource_1'=>'0',
                    'resource_2'=>'0',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'3',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'0',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'3',
                    'value_7'=>'3',
                    'value_8'=>'6',
                    'value_9'=>'2',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'3',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Sistemi informatici avanzati in dotazione alle navi di classe superiore.',
                    'dev_info'=>'',
            ), // Endof Component Interfaccia Biogenetica MK III

             // Component Interfaccia Biogenetica MK IV
             3=>array(
                    'name'=>'Interfaccia Biogenetica MK IV',
                    'resource_1'=>'300',
                    'resource_2'=>'0',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'2',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'0',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'4',
                    'value_7'=>'5',
                    'value_8'=>'6',
                    'value_9'=>'2',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'5',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'0',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Sistemi informatici estremamente avanzati e veloci disponibili per le navi ammiraglie.',
                    'dev_info'=>'',
            ), // Endof Component Interfaccia Biogenetica MK IV

      'name'=>'Sistema di elaborazione',
      'num'=>'4',
      ), // Endof Category Sistema di elaborazione


        // Category Trainingsraum
        6=>array(
             // Component Kampfsimulator MKI
             0=>array(
                    'name'=>'Simulatore combattimento MKI',
                    'resource_1'=>'1500',
                    'resource_2'=>'150',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'1',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'2',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'3',
                    'value_7'=>'1',
                    'value_8'=>'0',
                    'value_9'=>'5',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'1',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'1',
                    'torso_3'=>'1',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Il continuo addestramento in condizioni estreme permette di ottenere la miglior efficacia in combattimento possibile.',
                    'dev_info'=>'',
            ), // Endof Component Kortikalalarm

             // Component Kampfsimulator MKII
             1=>array(
                    'name'=>'Simulatore combattimento MKII',
                    'resource_1'=>'7500',
                    'resource_2'=>'3000',
                    'resource_3'=>'750',
                    'resource_4'=>'0',
                    'buildtime'=>'6',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'3',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'4',
                    'value_7'=>'3',
                    'value_8'=>'0',
                    'value_9'=>'4',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'2',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Il continuo addestramento in condizioni estreme permette di ottenere la miglior efficacia in combattimento possibile.',
                    'dev_info'=>'',
            ), // Endof Component Kortikaler Hypertransiver

             // Component Kampfsimulator MKIII
             2=>array(
                    'name'=>'Simulatore combattimento MKIII',
                    'resource_1'=>'2250',
                    'resource_2'=>'300',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'7',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'5',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'3',
                    'value_7'=>'3',
                    'value_8'=>'0',
                    'value_9'=>'6',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'4',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Il continuo addestramento in condizioni estreme permette di ottenere la miglior efficacia in combattimento possibile.',
                    'dev_info'=>'',
            ), // Endof Component Neurale Regeneration

              3=>array(
                    'name'=>'Simulatore combattimento MKIV',
                    'resource_1'=>'3000',
                    'resource_2'=>'375',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'7',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'1',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'8',
                    'value_7'=>'8',
                    'value_8'=>'2',
                    'value_9'=>'9',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'5',
                    'value_13'=>'0',
                    'value_14'=>'3',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'0',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Il continuo addestramento in condizioni estreme permette di ottenere la miglior efficacia in combattimento possibile.',
                    'dev_info'=>'',
            ),
            
            4=>array(
                    'name'=>'Simulatore combattimento MKV',
                    'resource_1'=>'250',
                    'resource_2'=>'125',
                    'resource_3'=>'25',
                    'resource_4'=>'0',
                    'buildtime'=>'7',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'2',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'3',
                    'value_7'=>'4',
                    'value_8'=>'0',
                    'value_9'=>'15',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'3',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'0',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Il continuo addestramento in condizioni estreme permette di ottenere la miglior efficacia in combattimento possibile.',
                    'dev_info'=>'',
            ),
            
      'name'=>'Area formazione',
      'num'=>'5',
      ), // Endof Category Trainingsraum


        // Category Wissenschaftssektion
        7=>array(
             // Component Fluider Torpedo
             0=>array(
                    'name'=>'Stazione sensori',
                    'resource_1'=>'2625',
                    'resource_2'=>'300',
                    'resource_3'=>'150',
                    'resource_4'=>'0',
                    'buildtime'=>'1',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'3',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'4',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'2',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'1',
                    'torso_3'=>'1',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Un comune banco di sensori a corto raggio.',
                    'dev_info'=>'',
            ), // Endof Component Fluider Torpedo

             // Component Erweiterte Sensoren
             1=>array(
                    'name'=>'Sensori avanzati',
                    'resource_1'=>'375',
                    'resource_2'=>'112.5',
                    'resource_3'=>'0',
                    'resource_4'=>'5',
                    'buildtime'=>'2',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'2',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'1',
                    'value_7'=>'1',
                    'value_8'=>'3',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'4',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'2',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Questa tipologia di sensori a medio raggio forniscono dati discretamente accurati.',
                    'dev_info'=>'',
            ), // Endof Component Fluider Torpedo II

             // Component Dual Sensorenstation
             2=>array(
                    'name'=>'Stazione sensori duale',
                    'resource_1'=>'975',
                    'resource_2'=>'225',
                    'resource_3'=>'0',
                    'resource_4'=>'5',
                    'buildtime'=>'2',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'0',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'4',
                    'value_12'=>'3',
                    'value_13'=>'0',
                    'value_14'=>'2',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Con questo componente, ogni stazione sensoriale contiene il numero doppio di sensori in grado di elaborare una quantit&agrave; maggiore di informazioni.',
                    'dev_info'=>'',
            ), // Endof Component Fluid-Plasma GeschEz

             // Component TiefenraumScaner
             3=>array(
                    'name'=>'Scanner spazio profondo',
                    'resource_1'=>'1275',
                    'resource_2'=>'300',
                    'resource_3'=>'37.5',
                    'resource_4'=>'0',
                    'buildtime'=>'4',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'0',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'2',
                    'value_7'=>'1',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'13',
                    'value_12'=>'15',
                    'value_13'=>'0',
                    'value_14'=>'3',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'0',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Questi scanner per lo spazio profondo rappresentano la punta di diamante dei nostri sensori. Aumentano in maniera considerevole la quantit&agravel e l&#146;accuratenzza dei dati acquisiti anche a lunghe distanze.',
                    'dev_info'=>'',
            ), // Endof Component

      'name'=>'Sezione scientifica',
      'num'=>'4',
      ), // Endof Category Schwere Waffen


        // Category  Experimentelles
        8=>array(
             // Component Energieschild
             0=>array(
                    'name'=>'Scudo energetico',
                    'resource_1'=>'2625',
                    'resource_2'=>'300',
                    'resource_3'=>'150',
                    'resource_4'=>'0',
                    'buildtime'=>'2',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'3',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'150',
                    'value_5'=>'0',
                    'value_6'=>'6',
                    'value_7'=>'6',
                    'value_8'=>'7',
                    'value_9'=>'2',
                    'value_10'=>'0',
                    'value_11'=>'7',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'5',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'0',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'The inertial dampers improve flight stability by generating an inertial field, which is the influence of gravitational forces in maneuvers reduced.',
                    'dev_info'=>'',
            ), // Endof Component

             // Component  Mehrphasen EdS
             1=>array(
                    'name'=>'More phases EdS',
                    'resource_1'=>'2625',
                    'resource_2'=>'300',
                    'resource_3'=>'150',
                    'resource_4'=>'0',
                    'buildtime'=>'3',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'2',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'15',
                    'value_5'=>'0',
                    'value_6'=>'1',
                    'value_7'=>'0',
                    'value_8'=>'5',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'2',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'0',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'Especially in the elite class concerted fields maximize the agility and response for optimal results.',
                    'dev_info'=>'',
            ), // Endof Component Tinoide Dämpfer

             // Component Bionisches Waffensystem MKI
             2=>array(
                    'name'=>'Sistema d&#146;arma bionico  MKI',
                    'resource_1'=>'375',
                    'resource_2'=>'0',
                    'resource_3'=>'0',
                    'resource_4'=>'0',
                    'buildtime'=>'4',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'2',
                    'unit_6'=>'0',
                    'value_1'=>'20',
                    'value_2'=>'50',
                    'value_3'=>'12',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'3',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'The tactical nerve pathways to improve the perception of the pilots of our ships. Thus, it is a light, to detect threats early.',
                    'dev_info'=>'',
            ), // Endof Component Taktische Nervenbahnen

             // Component Bionisches Waffensystem MKII
             3=>array(
                    'name'=>'Sistema d&#146;arma bionico  MKII',
                    'resource_1'=>'19500',
                    'resource_2'=>'11250',
                    'resource_3'=>'6000',
                    'resource_4'=>'60',
                    'buildtime'=>'5',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'5',
                    'unit_6'=>'0',
                    'value_1'=>'150',
                    'value_2'=>'95',
                    'value_3'=>'15',
                    'value_4'=>'150',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'3',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'0',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'The symbiosis Bioneurale connects the nerves of the pilots 1:1 with those of the ship. This will allow easier navigation, but there is the risk of permanent nerve damage from the pilots.',
                    'dev_info'=>'',
            ), // Endof Component Bioneurale Symbiose

             // Component  Energy damping Launcher
             4=>array(
                    'name'=>'Energy damping Launcher',
                    'resource_1'=>'7500',
                    'resource_2'=>'3000',
                    'resource_3'=>'750',
                    'resource_4'=>'0',
                    'buildtime'=>'7',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'4',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'100',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'0',
                    'value_13'=>'0',
                    'value_14'=>'3',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'By using bioneuraler control components could again be improved without the energy consumption to increase. They are specifically designed for the midium class.',
                    'dev_info'=>'',
            ), // Endof Component Energy damping Launcher

             // Component Erw.Tarnvorrichtung
             5=>array(
                    'name'=>'Erw.Tarnvorrichtung',
                    'resource_1'=>'7500',
                    'resource_2'=>'3000',
                    'resource_3'=>'750',
                    'resource_4'=>'20',
                    'buildtime'=>'8',
                    'unit_1'=>'0',
                    'unit_2'=>'0',
                    'unit_3'=>'0',
                    'unit_4'=>'0',
                    'unit_5'=>'1',
                    'unit_6'=>'0',
                    'value_1'=>'0',
                    'value_2'=>'0',
                    'value_3'=>'0',
                    'value_4'=>'0',
                    'value_5'=>'0',
                    'value_6'=>'0',
                    'value_7'=>'0',
                    'value_8'=>'0',
                    'value_9'=>'0',
                    'value_10'=>'0',
                    'value_11'=>'0',
                    'value_12'=>'10',
                    'value_13'=>'0',
                    'value_14'=>'4',
                    'value_15'=>'0',
                    'torso_1'=>'0',
                    'torso_2'=>'0',
                    'torso_3'=>'0',
                    'torso_4'=>'0',
                    'torso_5'=>'1',
                    'torso_6'=>'0',
                    'torso_7'=>'0',
                    'torso_8'=>'1',
                    'torso_9'=>'0',
                    'torso_10'=>'0',
                    'description'=>'In addition to the tactical system is actually an easy target enlargement. However, it draws on data from the database, which is a huge increase in firepower to follow.<br><tt>Requires: Advanced ship database</tt>',
                    'dev_info'=>'',
            ), // Endof Component Taktisches Nebensystem

            
      'name'=>' Sperimentale',
      'num'=>'6',
      ), // Endof Category  Experimental



), // Endof Race Breen



); // End of static-components
?>
