<?php
/*    
    This file is part of STFC.
    Copyright 2006-2007 by Michael Krauss (info@stfc2.de) and Tobias Gafner

    STFC is based on STGC,
    Copyright 2003-2007 by Florian Brede (florian_brede@hotmail.com) and Philipp Schmidt

    STFC is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    STFC is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


//########################################################################################
//########################################################################################

/* 26. May 2012
  @Author: Carolfi 
  @Action: Extends FPDF class in order to add a footer to the PDF document generated by
           the game.
*/

class myPDF extends FPDF
{
    var $page_str;
    var $web_str;

    function SetFooterData($website,$page)
    {
        $this->page_str = $page;
        $this->web_str  = $website;
    }

    function Footer()
    {
        //Go to 1 cm from bottom
        $this->SetY(-15);
        //Select Arial Italic 8
        $this->SetFont('Arial','I',8);
        $this->SetX(86,5);
        $this->Write(5, '[ powered by '.$this->web_str.']',$this->web_str);
        //Print centered page number
        $this->Cell(0,10,$this->page_str.' '.$this->PageNo(),0,0);
    }
}

?>
